### ISSUE TITLE
Syntax highlighting in HTML output broken for OCaml

### ISSUE THREAD

**Issue by tekknolagi** [zyedidia/Literate#10]
As seen in the screenshot below, the parser thinks that the bits in between the single quote marks is a string. In fact, this is a polymorphic data structure with type argument `'a`.

<img width="888" alt="screen shot 2016-07-02 at 1 57 28 pm" src="https://cloud.githubusercontent.com/assets/401167/16542435/0e94d444-405d-11e6-9361-b813ce1030e2.png">

I declared `@code_type ocaml ml` and also tried `caml`, `sml`, etc — but none helped the problem.

**Comment by zyedidia** [comment]
The extension in the `@code_type` expression is written with a `.` at the start to emphasize the fact that it is an extension. So the you should declare `@code_type ocaml .ml` for the syntax highlighter to know the extension of the language.

Perhaps it would be good to give a warning if the extension is given without a `.`.

**Comment by tekknolagi** [comment]
@zyedidia Ohhh, I feel stupid. Thank you!
