### ISSUE TITLE
Pipe output of code into the html document

### ISSUE THREAD

**Issue by BlackEdder** [zyedidia/Literate#11]
It would be great if there was some way of "piping" code output to html. Currently I do this by writing to a file in an assets directory and then including that file.

One simple approach that would already help is to have a way to generate unique filenames, so that you can save to @{uuid 1} in the code and later include @{uuid 1} or a similar approach.

**Comment by zyedidia** [comment]
I'm not sure I understand what you mean. Are you asking for a way to have Literate run some arbitrary code in the Literate file which would determine the filename of the output file?

I think I would have an easier time understanding if you gave a concrete example of what exactly you'd like to be able to do.

**Comment by BlackEdder** [comment]
My use case is slightly beyond the original design of literate, since I use it to do data analysis (similar to Rmarkdown for R). That way I can have the code doing the analysis together with a description of what the code is doing. Where I go beyond the original design of literate is that I'd also show the results of the analysis (code) in the same documents. For now I mostly do that by creating plots in the code (with ggplotd) and then including those plots in the markdown

```
---
// Do some data analysis
plot_result( "assets/location_of_plot.png" )
---

![plot title](assets/location_of_plot.png)
```

Similarly I have a function that turns tables into markdown tables (as supported by pandoc). I can then include the resulting markdown into the document. So this all works reasonably well. I was just wondering if there might be a way to make this a bit smoother.

**Comment by zyedidia** [comment]
Yeah I think what you're doing right now is best. You could make a small bash script to do that in one command if you wanted:

```
lit -t your_code.lit
# compile the generated code...
# run the generated code...
# store the file in assets/location_of_plot.png
lit -w your_code.lit
```
