### ISSUE TITLE
Feature request: noTangle block modifier

### ISSUE THREAD

**Issue by ifigueroap** [zyedidia/Literate#13]
As a counterpart to the `noWeave` block modifier it would be quite useful to have a `noTangle` modifier, for when you want code blocks to appear only in the documentation (e.g. examples, non-compiling code) but not in the actually generated files...

**Comment by zyedidia** [comment]
You can effectively achieve this by never linking the code block into the program.

**Comment by ifigueroap** [comment]
I'm sorry, perhaps I don't understand what you mean... I currently have something like this:

```
--- example.c
int main () {
   // some sample I don't care about, or maybe it doesn't compile
}
---
```

And I'm using a Makefile to compile al .c files, I have the following rule:

```
%.o: %.c
	gcc -I/usr/local/include/SL $(CFLAGS) -c -o $@ $^
	rm *.o
```

So under this setting, I would still have to compile the `example.c` file, because it is generated when running lit. That's why I would like to do:

```
--- example.c --- noTangle
int main () {
   // some sample I don't care about, or maybe it doesn't compile
}
---
```

So I can keep using the general Makefile rule. Does this make sense?
Thanks

**Comment by zyedidia** [comment]
Ok I see. Currently, Literate identifies the code block as a file code block because it has a filename for a name (`example.c`). If you rename the code block to something else, like `example` or `C example`, then it won't be generated when running lit because it isn't a filename and it isn't linked to any filename blocks.

**Comment by ifigueroap** [comment]
I see, that should be enough, but what is the precise definition (regexp?) for a "filename" ?

**Comment by zyedidia** [comment]
Basically it's anything ending with `.*` or if you put the name in quotes, then Literate will treat it as a file (even if there is no extension).

Here is the precise regexp: `.*\.\w+`
