### ISSUE TITLE
@include misplaces content. [Describing things is hard]

### ISSUE THREAD

**Issue by BorisKourt** [zyedidia/Literate#2]
### The main file:

```lit
@code_type clojure .clj
@comment_type ;; %s

@title Hello Clojure

@s Section

--- example.clj
(ns user)
@{a function}
@{main}
---

@s The meat and potatoes!

--- a function
(defn hello [hi]
(println hi))
---

@s Some other thing!

--- main
(defn -main [& args])
---

@include hello_java.lit
```
#### hello_java.lit

```lit 
@code_type java .java
@comment_type // %s

@title Name

@s Introduction

--- name.java
// Hello World, World.
---
```

### HTML output:

![ss_lit](https://cloud.githubusercontent.com/assets/1929082/12856129/564f9ac8-cc11-11e5-86b6-4d1334e88459.png)

The included `hello_java.lit` file ends up being between sections `Another` and `Some other thing!`, rather than right after `Some other thing!`. 

I tested this by moving the `@include` statement below each of the sections and it always imports above the section it is below.

***

Anothing thing I noticed: the `1. Introduction` anchor (from the included file) is the same as `1. Section`, so it conflicts with linking to section `1`.

**Comment by BorisKourt** [comment]
Wait was this just fixed by https://github.com/zyedidia/Literate/commit/df9cd08314ac6554791819773ebf6f1b4ca1cd89? I can't try it just yet, but will try tonight.

**Comment by zyedidia** [comment]
This should be fixed now. Make sure to rebuild with `make` after you pull.
