### ISSUE TITLE
Output file sub directories

### ISSUE THREAD

**Issue by branscha** [zyedidia/Literate#51]
It would be nice if the output file specification for  a code block could include a sub directory which would be created while tangling. It would be handy for languages like Java where the sources have to be in a directory tree.

Example
```
--- src/main/java/com/acme/Hello.java
CODE
---
```

**Comment by brikis98** [comment]
+1!

**Comment by zyedidia** [comment]
Merged #46.

**Comment by brikis98** [comment]
Thanks for getting that implemented!

**Comment by branscha** [comment]
Yes, fantastic, it works like a charm. Thanks.
